一个插件
MCDReforged-Plugins/PluginCatalogue pull request #71
Opened 2020-09-01 15:40 UTC by W-Kazdel

保护伪和平安全

2020-09-01 23:08 UTC, zhang-anzhi commented
作者错误

2020-09-01 23:12 UTC, zhang-anzhi requested changes

2020-09-01 23:12 UTC, zhang-anzhi commented on readme_cn.md
> +| [Monitor](https://github.com/W-Kazdel/Monitor) | [W-Kazdel](https://github.com/ChunkAsgore) | 记录玩家坐标，伪和平通知 |
请修改作者信息

2020-09-01 23:12 UTC, zhang-anzhi commented on readme.md
> +| [Monitor](https://github.com/W-Kazdel/Monitor) | [W-Kazdel](https://github.com/ChunkAsgore) | Record player coordinates, pseudo-peace notification. |
请修改作者信息

2020-09-02 12:24 UTC, W-Kazdel commented on readme_cn.md
> +| [Monitor](https://github.com/W-Kazdel/Monitor) | [W-Kazdel](https://github.com/ChunkAsgore) | 记录玩家坐标，伪和平通知 |
修改完成

2020-09-02 14:10 UTC, W-Kazdel commented on readme.md
> +| [Monitor](https://github.com/W-Kazdel/Monitor) | [W-Kazdel](https://github.com/ChunkAsgore) | Record player coordinates, pseudo-peace notification. |
修改完成

2020-09-02 14:10 UTC, W-Kazdel commented
作者修改完成

2020-09-02 23:26 UTC, merged