BilibiliInfo 一个哔哩哔哩插件
MCDReforged-Plugins/PluginCatalogue pull request #75
Opened 2020-11-23 14:17 UTC by CalciumSilicate

在游戏公屏打出BV，AV或B站视频链接，得到视频的点赞，弹幕，评论，收藏，硬币，分享和播放量，并给出直接跳转浏览器的按钮和复制BV，AV或B站视频链接的按钮

2020-11-23 23:41 UTC, zhang-anzhi commented
这个是否应该算娱乐呢？

2020-12-12 12:13 UTC, hanbings commented
应该是属于娱乐的 信息获取板块都是游戏内获取的 如果把这个放进去感觉有点突兀

2020-12-12 12:42 UTC, zhang-anzhi requested changes
This plugin should be in Recreation.

2020-12-12 12:42 UTC, zhang-anzhi commented on readme.md
> +| [BilibiliInfo](https://github.com/CalciumSilicate/BilibiliInfo) | [CalciumSilicate](https://github.com/CalciumSilicate) | Another Bilibili plugin to parse Bilibili information and get the result on
Move to Recreation.

2020-12-12 12:42 UTC, zhang-anzhi commented on readme_cn.md
> +| [BilibiliInfo](https://github.com/CalciumSilicate/BilibiliInfo) | [CalciumSilicate](https://github.com/CalciumSilicate) | 另一个哔哩哔哩插件，查询信息并给出视频点击按钮而不是重新打BV号等 |
Move to Recreation.

2020-12-13 02:05 UTC, merged